### ISSUE TITLE
Add Dispersement search Node to graphql-api

### ISSUE THREAD

**Issue by calebbriggs** [braintree/graphql-api#10]
We are trying to get better at telling our clients what has been dispersed to their account, when, and and for what. A Dispersement search node query would be extremely helpful to accomplish this task

**Comment by lkorth** [comment]
@calebbriggs are you asking for a `Disbursement` type that contains `DisbursementDetails` and an `ID` so it can be retrieved via a `node` query, or a `Disbursement` type and search query that has several inputs for the various values disbursements have and returns the ones that match?

**Comment by lkorth** [comment]
@calebbriggs I'm closing this due to lack of further clarification. If you'd like to add more information about your request we'll be happy to reopen it.
