### ISSUE TITLE
Charging fake-valid-dinersclub-nonce returns brandCode DISCOVER

### ISSUE THREAD

**Issue by iki** [braintree/graphql-api#11]
Try in [explorer](https://graphql.braintreepayments.com/explorer/):
```graphql
mutation {
  chargePaymentMethod(
    input: {
      paymentMethodId: "fake-valid-dinersclub-nonce",
      transaction: {
        amount: "1.23",
      },
    }
  ) {
    transaction {
      id
      status
      createdAt
      paymentMethodSnapshot {
        ... on CreditCardDetails {
          brandCode
          last4
          expirationMonth
          expirationYear
        }
      }
    }
  }
}
```

**Comment by iki** [comment]
Also `fake-processor-declined-visa-nonce` returns status `SUBMITTED_FOR_SETTLEMENT`.

Didn't test other [testing nonces](https://developers.braintreepayments.com/reference/general/testing/node#nonces-for-testing-card-verification) that should be rejected

**Comment by lkorth** [comment]
There is [a footnote in the docs that mentions Diners Club cards are processed as Discover cards](https://developers.braintreepayments.com/reference/general/testing/#test-value-36259600000004) a bit above the section that lists test nonces. The same is true here for the GraphQL API.

There is also [a note](https://developers.braintreepayments.com/reference/general/testing/#nonces-representing-cards) at the top of the test nonce section that states

>When testing card verifications and transactions, keep in mind:
>  * Transaction success is determined by the test amount you use
>  * Verification success is determined by the test nonce you use

You'll want to use a test amount to trigger an authorization decline, the test card nonces that decline are for verifications.

**Comment by iki** [comment]
Thanks for explanation @lkorth !
