### ISSUE TITLE
Documention - Relay Input Object Mutations Specification

### ISSUE THREAD

**Issue by math-nao** [braintree/graphql-api#12]
Firstly, the link to relay documentation about "Relay Input Object Mutations Specification" is broken.

Secondly, RelayModern does not need `clientMutationId` and it has been removed from documentation since RelayModern v8.0.0 (https://github.com/facebook/relay/commit/3838691f4f815ce90b6d544fa052b112259a4c9a). It was required for RelayClassic. Could you at least state that it is for RelayClassic support? I'm only using RelayModern and I spent time to figure out that is for RelayClassic only.

Doc lInk: https://graphql.braintreepayments.com/guides/making_api_calls/#a-more-interesting-request

**Comment by alexgenco** [comment]
Thanks @math-nao we will update our docs accordingly.

**Comment by alexgenco** [comment]
We've removed references to `clientMutationId` from the guides to prevent this confusion for the time being.
