### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by MFALHI** [braintree/graphql-api#14]
Je demande le service paypal au Maroc

**Comment by lkorth** [comment]
Issues in this repo are meant to be for feature requests or bugs with the GraphQL API, if you have a question or request outside of the GraphQL API, please reach out to our [Braintree](https://help.braintreepayments.com/) or [PayPal](https://developer.paypal.com/support/) support.

Les problèmes dans ce référentiel sont destinés à être des demandes de fonctionnalités ou des bogues avec l'API GraphQL, si vous avez une question ou une demande en dehors de l'API GraphQL, veuillez contacter notre [Braintree](https://help.braintreepayments.com/ ) ou [PayPal](https://developer.paypal.com/support/).
