### ISSUE TITLE
Creation of sub-merchant

### ISSUE THREAD

**Issue by sajadghawami** [braintree/graphql-api#16]
Hey there,

we are currently evaluating whether or not we should integrate the GraphQL-Api - which looks awesome by the way - or if we should integrate one of the SDKs.

One of the things we could not find in the current GraphQL-Implementation is the creation of sub-merchant, or merchant accounts in general.

The SDKs seem to support this:

https://developers.braintreepayments.com/guides/braintree-marketplace/onboarding/node

Am i missing something, or has the API not been fully ported to GraphQL yet?

Thanks!

**Comment by lkorth** [comment]
Hi @sajadghawami, sorry for the wait, we've been busy working on a few things related to this.

There are some products that we don't have any plans to support in the GraphQL API as we're generally not adding any new users of that product, marketplace is one of these. However we have been working on some new mutations for creating merchant accounts, they're not generally available at this time, but I'd encourage you to speak with anyone you've already been talking to in sales or support or reach out at https://www.braintreepayments.com/contact/sales to talk about your needs and to see if these new mutations will work for you.
