### ISSUE TITLE
Query Viewer

### ISSUE THREAD

**Issue by miguelBarreiro85** [braintree/graphql-api#23]
field rights should expect Rights and is expecting String, throwing errors on compilers

**Comment by lkorth** [comment]
I assume you're referring to the [`rights` field on the `Viewer` type](https://github.com/braintree/graphql-api/blob/f5a20a6b6ea5e55ce3404afe2a2f84c648437578/schema.graphql#L9436)?

We just deployed a change to switch this to `[Right!]`, it should not have been `[String!]`
