### ISSUE TITLE
Supporting three_d_secure_pass_thru parameters

### ISSUE THREAD

**Issue by snaptravel** [braintree/graphql-api#3]
Hi Braintree,

With the upcoming PSD2 deadline on Sept 14th, we would like to request support for the [three_d_secure_pass_thru](https://developers.braintreepayments.com/reference/request/transaction/sale/python) parameters in the API so that we can use the GraphQL API for 3DS transactions.

Thank you!

**Comment by miriam** [comment]
Thanks for bringing this up @snaptravel. It's on our to-do list! When it hits the prod API, it'll show up in the schema here :-)

**Comment by lkorth** [comment]
@snaptravel 3D Secure pass through fields are now available, thank you for the feature request!
