### ISSUE TITLE
Add Customer Search

### ISSUE THREAD

**Issue by GimignanoF** [braintree/graphql-api#4]
I'm trying to implement the GraphAPI in my project, and i need to search through transactions given customer email and/or name (like you can do from the control panel). However i see that the transactions search query only accepts the customer id, and i can't find another query to get the custom id given the email or the name. So how can i retrieve transactions given some customer details, or at least give the customer id given them in Graph?

**Comment by lkorth** [comment]
@GimignanoF customer search or transaction search with customer details does not currently exist in the API, but it is on our roadmap. As you've already found, once you have the customer ID you can either use transaction search or a customer node query to get the customer's transactions. 

Until customer search or transaction search with customer details is part of the API, you'll either need to store the customer IDs or use one of server SDKs to leverage customer search.

**Comment by GimignanoF** [comment]
Got it, i hope this feature will come soon so i can move to using the graph implementation :)

**Comment by lkorth** [comment]
@GimignanoF I'm going to leave this issue open and we'll close it when the feature is part of the API.

**Comment by translatorzepp** [comment]
@GimignanoF Searching for customers is now available—thanks for the request!

**Comment by GimignanoF** [comment]
Glad to hear that! :D Can't wait to implement that in my services :)
