### ISSUE TITLE
Unknown type partialCaptureTransactionInput

### ISSUE THREAD

**Issue by orial07** [braintree/graphql-api#7]
Hello, I am trying to use the partialCaptureTransaction, and been using the example given in the BrainTree documentation but it is not working it gives an error
   "message": "Validation error of type UnknownType: Unknown type partialCaptureTransactionInput",
      "message": "Validation error of type FieldUndefined: Field 'transaction' in type 'PartialCaptureTransactionPayload' is undefined @ 'partialCaptureTransaction/transaction'",

Example used: https://graphql.braintreepayments.com/guides/creating_transactions/#using-multiple-partial-capture

**Comment by lkorth** [comment]
@orial07 The variables in that example are actually wrong. The correct variables for it are:

```json
{
  "input": {
    "transactionId": "id_of_authorized_transaction",
    "transaction": {
      "amount": "5.45"
    } 
  }
}
```

I've updated the docs to fix this and the fix will be release in the near future.
