### ISSUE TITLE
Difference between object attributes in graphql and sdk

### ISSUE THREAD

**Issue by aminvakhshouri** [braintree/graphql-api#8]
Hi, I wonder if there is a way to retrieve the exact same attribute from objects in graphql as that of SDKs.
For example, `Merchant` object has the following fields in graphql:
`id,status,companyName,Company name,website,timezone`
Whereas, in python SDK,  `merchant_account_gateway` provides an extra set of objects with multiple attributes such as `business_details`, `individual_details` and `funding_details`. 
I suppose, we can retrieve the same objects and fileds from both SDK and graphql. 

Could you provide more information on how to fetch additional fields with graphql API?

**Comment by lkorth** [comment]
It is not currently possible to retrieve fields such as `business_details`, `individual_details`, etc, they do not exist in the GraphQL API. What you see in the schema are the fields that exist in the API.

If you'd like to turn this into a request for those additional fields on `Merchant` I can leave this open to track this feature request.

**Comment by lkorth** [comment]
@aminvakhshouri I'm closing this old issue. If you'd like to add a list of the fields you're looking for we'll be happy to reopen it and mark it as a feature request.
